# SPDX-License-Identifier: Apache-2.0

version: "3.6"

services:
  jekyll:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ..:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t
